### ISSUE TITLE
Enhance API authentication

### ISSUE THREAD

**Issue by caroseuk** [caroseuk/simple-ruby-api#1]
If anybody has any good Ruby/Sinatra skills and knows of a way to store user credentials (in MySQL) so that I can enhance the api with auth, please feel free to fork it and send a pull request!

**Comment by omegahm** [comment]
Could you elaborate a bit? 

You want a table with users (username and encrypted passwords) so that all the requests are authenticated against this table before sending a reply?

**Comment by caroseuk** [comment]
That’s correct, currently it’s hard coded for one user/password but it would be great to have a users table that allows an admin to add multiple users to use the api ☺️
